routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Para las traducciones en nuestra web
Route::get('/set_language/{lang}', 'Controller@setLanguage')->name( 'set_language');

// Rutas para el login/{recibira un driver bien facebook o github}
Route::get('login/{driver}', 'Auth\LoginController@redirectToProvider')->name('social_auth');
Route::get('login/{driver}/callback', 'Auth\LoginController@handleProviderCallback');

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

// Ruta para la obtener la ruta la imagen
Route::get('/images/{path}/{attachment}', function($path, $attachment) {
    $file = sprintf('storage/%s/%s', $path, $attachment);
    // storage/%s/%s => como vemos se genera  en public/store/courses|%s|$path/imagenes|%s|$attachment
    if(File::exists($file)) {
        return Image::make($file)->response();
    }
});


// Rutas para obtener y procesar la suscripcion
Route::group(['middleware' => ['auth']], function () {
    Route::group(["prefix" => "subscriptions"], function() {
        Route::get('/plans', 'SubscriptionController@plans')
            ->name('subscriptions.plans');
        // Ruta luego de suscribirse
        Route::get('/admin', 'SubscriptionController@admin')
            ->name('subscriptions.admin');

        Route::post('/process_subscription', 'SubscriptionController@processSubscription')
            ->name('subscriptions.process_subscription');
        // Rutas para renaudar y cancelar suscripcion
        Route::post('/resume', 'SubscriptionController@resume')->name('subscriptions.resume');
        Route::post('/cancel', 'SubscriptionController@cancel')->name('subscriptions.cancel');

    });
    // Para las facturas
    Route::group(['prefix' => "invoices"], function() {
        // Para poder administrarla
        Route::get('/admin', 'InvoiceController@admin')->name('invoices.admin');
        // Para poder descargar las facturas
        Route::get('/{invoice}/download', 'InvoiceController@download')->name('invoices.download');
    });
});
/*
 * Luego ejecutas un enlace simbolico para utilizar el directorio store de la imagem
 * en terminal ejecutas la ruta
 * php artisan storage:link
 * */

// Creamos un grupo de rutas de courses y le paso un parametro a la vista
Route::group(['prefix' => 'courses'], function () {
    Route::group(['middleware' => ['auth']], function() {
        // Para obtener las suscribirse al curso que sea sacado de la tabla course_student
        Route::get('/subscribed', 'CoursesController@subscribed')->name('courses.subscribed');
        Route::get('/{course}/inscribe', 'CoursesController@inscribe')->name('courses.inscribe');
        // Para procesar las reseñas de los cursos
        Route::post('/add_review', 'CoursesController@addReview')->name('courses.add_review');
        // Usamos el middleware con una funcion sprintf (parametro1 , parametro 2)
        // (nombre del middleware [en mi caso role] luego con :$s es segundo parametro que en este caso
        // sera \App\Role::TEACHER el rol Teacher que es sacado del modelo Role) y ademas usaremos todos los metodos con resource
        // index,store,create,destroy,update,show
        Route::group(['middleware' => [sprintf('role:%s', \App\Role::TEACHER)]], function () {
          Route::resource('courses', 'CoursesController');
       });

    });
    Route::get('/{course}', 'CoursesController@show')->name('courses.detail');
});

// Ruta para gestionar a los usuarios
Route::group(["prefix" => "profile", "middleware" => ["auth"]], function() {
    Route::get('/', 'ProfileController@index')->name('profile.index');
    Route::put('/', 'ProfileController@update')->name('profile.update');
});

// Para poder hacer solicitud para sea profesor
Route::group(['prefix' => "solicitude"], function() {
    Route::post('/teacher', 'SolicitudeController@teacher')->name('solicitude.teacher');
});

//  Obtener los cursos y estydiantes que pertenecer al profesor
Route::group(['prefix' => "teacher", "middleware" => ["auth"]], function() {
    // Ruta para que liste los cursos que imparte el teacher y se lista asociando al teacher
    Route::get('/courses', 'TeacherController@courses')->name('teacher.courses');
    Route::get('/students', 'TeacherController@students')->name('teacher.students');
    // ruta para enviar el mensaje tipo post
    Route::post('/send_message_to_student', 'TeacherController@sendMessageToStudent')->name('teacher.send_message_to_student');

});

// Rutas para solo los administradores y autentificados
Route::group(['prefix' => "admin", "middleware" => ['auth', sprintf("role:%s", \App\Role::ADMIN)]], function() {
    // para mostrar el componente que vamos a generar con vue.js
    Route::get('/courses', 'AdminController@courses')->name('admin.courses');
    // obtener los datos de los cursos en formato json
    Route::get('/courses_json', 'AdminController@coursesJson')->name('admin.courses_json');
    // actualizar el estado del curso y enciar un email al profesor si se ha publicado o sea ha rechazado
    Route::post('/courses/updateStatus', 'AdminController@updateCourseStatus');

    Route::get('/students', 'AdminController@students')->name('admin.students');
    Route::get('/students_json', 'AdminController@studentsJson')->name('admin.students_json');
    Route::get('/teachers', 'AdminController@teachers')->name('admin.teachers');
    Route::get('/teachers_json', 'AdminController@teachersJson')->name('admin.teachers_json');
});

app/Http/Controllers/CoursesController.php
<?php

namespace App\Http\Controllers;

use App\Course;
use App\Review;
use Illuminate\Http\Request;
use App\Mail\NewStudentInCourse;

use App\Helpers\Helper;

use App\Http\Requests\CourseRequest;

class CoursesController extends Controller
{
  //   /{course} => como vemos le paso todos el parametro
    //  y lo pinto en pantalla con dd
    public function show (Course $course) {
        // con load obtengo las relaciones de las demas tablas con el curso

        $course->load([
            'category' => function ($q) {
                $q->select('id', 'name');
            },
            'goals' => function ($q) {
                $q->select('id', 'course_id', 'goal');
            },
            'level' => function ($q) {
                $q->select('id', 'name');
            },
            'requirements' => function ($q) {
                $q->select('id', 'course_id', 'requirement');
            },
            'reviews.user',
            'teacher'
        ])->get();
         $related =  $course->relatedCourses();
        return view('courses.detail', compact('course', 'related'));


//        http://dev.learning:8080/courses/qui-sit-explicabo-mollitia-nemo-quae
        // asi se mostrara en pantalla con el slug que le declare  getRouteKeyName() en course
    }

    public function inscribe (Course $course) {
        // dentro de la tabla course_student insertar el id del estudiante
        $course->students()->attach(auth()->user()->student->id);
        // Te acuerdas Mail/NewStudentInCourse en ese constructr mandas 2 parametreos pz
        // aqui vemos que se le pasara  public function __construct(Course $course, $student_name)
        // el primero esta claro con todos los parametros del curso y en $student_name se enviara
        //  auth()->user()->name del estuidante en este caso el nombre del usuario estudiante

        // to => sera enviado al teacher con los datos del curso que se inscribio es estudiante

        \Mail::to($course->teacher->user)->send(new NewStudentInCourse($course, auth()->user()->name));
        return back()->with('message', ['success', __("Inscrito correctamente al curso")]);
    }

    public function subscribed () {
        // creo una variable para que este curso tenga estudiantes
        $courses = Course::whereHas('students', function($query) {
            // ademas que me y dentro de la tabla students
            // me seleccione el user_id que sera el id de mi autentificacion
            $query->where('user_id', auth()->id());
        })->get();
        // Manda a la vista con la variable courses
        return view('courses.subscribed', compact('courses'));
    }

    public function addReview () {
        // Pasaremos un array y lo creamos con un request pasamos este formulario post
        Review::create([
            "user_id" => auth()->id(),
            "course_id" => request('course_id'),
            // castemos a un input
            "rating" => (int) request('rating_input'),
            "comment" => request('message')
        ]);
        return back()->with('message', ['success', __('Muchas gracias por valorar el curso')]);
    }

    public function create()
    {
        $course = new Course;
        $btnText = __("Enviar Curso para revision");
        return view('courses.form',compact('course','btnText'));
        
    }

    public function store (CourseRequest $course_request) {
/*        // si ha pasado la validacion se muestra en la pantalla con los datos obtenidos
            dd($course_request->all());*/

        // Aqui usamos los parametros que habias creado en nuestro helper
        // donde key = picture(nombre del archivo  ) y path (ruta del archivo)
        // subida del archivo uploadFile
        $picture = Helper::uploadFile('picture', 'courses');
        // dentro de la peticion $course_request exista una nueva varible 'picture'
        // con merge le pasamos un array donde va hacer el valor $picture
        $course_request->merge(['picture' => $picture]);
        // conseguimos el id del teacher que crea el curso
        $course_request->merge(['teacher_id' => auth()->user()->teacher->id]);
        // el curso esta en pendiento
        $course_request->merge(['status' => Course::PENDING]);
        // insertar en la tabla Course toda la infromacion del  $course_request
        Course::create($course_request->input());

        // luego enviamos un mensaje de exito de envio
        return back()->with('message', ['success', __('Curso enviado correctamente, recibirá un correo con cualquier información')]);


    }

    public function edit ($slug) {
        // Esta funcion para visualizar el editar y te cargue los datos en pantalla
        // juntamentente con las relaciones de requirements goals
        // y para tambien contar los requirements y goals
        // para luego utilizarlo requirements_count t goals_count
        $course = Course::with(['requirements', 'goals'])->withCount(['requirements', 'goals'])
            ->whereSlug($slug)->first();
        $btnText = __("Actualizar curso");
        return view('courses.form', compact('course', 'btnText'));
    }

    public function update (CourseRequest $course_request, Course $course) {

        // si deseas primero  le envias
        // dd($course); para ver los datos que se envian y darle click haber que se muestra en pantalla

        // si es que subimos un archivo va a tener que eliminar la imagen que que tenenia anteriormente
        // para luego subirla y darle la ruta
        // y con merge vamos a guardarla en un array
        if($course_request->hasFile('picture')) {
            \Storage::delete('courses/' . $course->picture);
            $picture = Helper::uploadFile( "picture", 'courses');
            $course_request->merge(['picture' => $picture]);
        }
        // con fill vamos a guardar todos los input a la BD
        $course->fill($course_request->input())->save();
        return back()->with('message', ['success', __('Curso actualizado')]);
    }
    public function destroy (Course $course) {
        try {
            $course->delete();
            return back()->with('message', ['success', __("Curso eliminado correctamente")]);
        } catch (\Exception $exception) {
            return back()->with('message', ['danger', __("Error eliminando el curso")]);
        }
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Course;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        // Para accceder a la vista home primero tenemos autenficarnos pero con excep
        // le vamos a dar permiso para que solo la vista index este permitida por todos
        $this->middleware('auth')->except(['index']);
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // withCount : coger el conteo
        $courses = Course::withCount(['students'])
            // a la vez con las relaciones que estableciomos en el modelo curso
            ->with('category', 'teacher', 'reviews')
            // todos los cursos con estado publicado
            ->where('status', Course::PUBLISHED)
            // descendente
            // ->latest() descendde por created_at
            ->oldest() //  ascendente por created_at
            ->paginate(12);

        return view('home',compact('courses'));
    }
}

resources/views/partials/courses/action_button.blade.php
<div class="col-2">
    @auth
        @can('opt_for_course', $course)
          {{-- Si el usuario es diferente de profesor
             o el usuario id del teacher es discinto al teacher_id del curso--}}
             @can('subscribe', \App\Course::class)
              {{--   si el rol es distinto a adminnistrador ya que este este tendra acceso a all
                 y tambien el usuario no este suscrito a una suscripcion --}}
                <a class="btn btn-subscribe btn-bottom btn-block" href="{{route('subscriptions.plans')  }}">
                    <i class="fa fa-bolt"></i> {{ __("Subscribirme") }}
                </a>
             @else
                {{--  Si no se cumple  ---  si el rol es igua  a adminnistrador ya que este este tendra acceso a all
               y tambien el usuario no este suscrito a una suscripcion el usuario puede inscribirse al curso  --}}
                 @can('inscribe', $course)
                    <a class="btn btn-subscribe btn-bottom btn-block" href="{{ route('courses.inscribe', ['slug' => $course->slug]) }}">
                        <i class="fa fa-bolt"></i> {{ __("Inscribirme") }}
                    </a>
                 @else
                    <a class="btn btn-subscribe btn-bottom btn-block" href="#">
                        <i class="fa fa-bolt"></i> {{ __("Inscrito") }}
                    </a>
                 @endcan
             @endcan

        @else
            {{-- Si esto no se cumple eres autor --- Si el usuario es diferente de profesor
            o el usuario id del teacher es discinto al teacher_id del curso--}}
            <a class="btn btn-subscribe btn-bottom btn-block" href="#">
                <i class="fa fa-user"></i> {{ __("Soy autor") }}
            </a>

        @endcan

    @else
        <a class="btn btn-subscribe btn-bottom btn-block" href="{{ route('login') }}">
            <i class="fa fa-user"></i> {{ __("Acceder") }}
        </a>


    @endauth
</div>

resources/views/partials/courses/card_course.blade.php
<div class="card card-01">
    <img
        class="card-img-top"
        src="{{ $course->pathAttachment() }}"
        alt="{{ $course->name }}"
    />
    <div class="card-body">
        <span class="badge-box"><i class="fa fa-check"></i></span>
        <h4 class="card-title">{{ $course->name }}</h4>
        <hr />
        <div class="row justify-content-center">
            {{--Añadir el parcial del rating --}}
            {{--En nuestra vista partials.courses.rating hay una variable
            $rating que va determinar el puntaje del rating por eso aqui le declaramos ['rating' => ]
            y para eso $course->custom_rating] el custom_rating se obtendra del metodo
             getCustomRatingAttribute para poder obtenerlo--}}
            @include('partials.courses.rating', ['rating' => $course->custom_rating])
        </div>
        <hr />
        <span class="badge badge-danger badge-cat">{{ $course->category->name }}</span>
        <p class="card-text">
            {{ str_limit($course->description, 100) }}
        </p>
        <a
            href="{{ route('courses.detail', $course->slug) }}"
            class="btn btn-course btn-block"
        >
            {{ __("Más información") }}
        </a>
    </div>
</div>

resources/views/partials/courses/description.blade.php
<div class="col-12 pt-0 mt-0">
    <h2 class="text-muted">{{ __("¿Qué vamos a hacer?") }}</h2>
    <hr />
</div>
<div class="col-12">
    <p class="mb-0">
        {{ $course->description }}
    </p>
</div>

resources/views/partials/courses/form_review.blade.php
{{--Solo para usuarios que sean escrito a los cursos pueden dar una valoracion --}}
@cannot('inscribe', $course)
    @can('review', $course)
        <div class="col-12 pt-0 mt-4 text-center">
            <h2 class="text-muted">{{ __("Escribe una valoración") }}</h2><hr />
        </div>

        <div class="container-fluid">
            <form method="POST" action="{{ route('courses.add_review') }}" class="form-inline" id="rating_form">
                @csrf
                <div class="form-group">
                    <div class="col-12">
                        <ul id="list_rating" class="list-inline" style="font-size: 40px;">
                            <li class="list-inline-item star" data-number="1"><i class="fa fa-star yellow"></i></li>
                            <li class="list-inline-item star" data-number="2"><i class="fa fa-star"></i></li>
                            <li class="list-inline-item star" data-number="3"><i class="fa fa-star"></i></li>
                            <li class="list-inline-item star" data-number="4"><i class="fa fa-star"></i></li>
                            <li class="list-inline-item star" data-number="5"><i class="fa fa-star"></i></li>
                        </ul>
                    </div>
                </div>

                <br />

                <input type="hidden" name="rating_input" value="1" />
                <input type="hidden" name="course_id" value="{{ $course->id }}" />

                <div class="form-group">
                    <div class="col-12">
                        <textarea
                            placeholder="{{ __("Escribe una reseña") }}"
                            id="message"
                            name="message"
                            class="form-control"
                            rows="8"
                            cols="120"
                        ></textarea>
                    </div>
                </div>

                <button type="submit" class="btn btn-warning text-white">
                    <i class="fa fa-space-shuttle"></i> {{ __("Valorar curso") }}
                </button>
            </form>
        </div>
    @endcan
@endcannot
{{--@stack('scripts') gracias @stack en app.blade
 puedo invocar aqui en plantilla blade solo llamandolo --}}
@push('scripts')
    <script>
        jQuery(document).ready(function() {
            const ratingSelector = jQuery('#list_rating');
            ratingSelector.find('li').on('click', function () {
                const number = $(this).data('number');
                $("#rating_form").find('input[name=rating_input]').val(number);
                ratingSelector.find('li i').removeClass('yellow').each(function(index) {
                    if ((index + 1) <= number) {
                        $(this).addClass('yellow');
                    }
                })
            })
        });
    </script>
@endpush

resources/views/partials/courses/goals.blade.php
<div class="col-12 pt-0 mt-0">
    <h2 class="text-muted">{{ __("Metas del curso") }}</h2>
    <hr />
</div>
@forelse($goals as $goal)
    <div class="col-6">
        <div class="card bg-light p-3">
            <p class="mb-0">
                {{ $goal->goal }}
            </p>
        </div>
    </div>
@empty
    <div class="alert alert-dark">
        <i class="fa fa-info-circle"></i>
        {{ __("No se han escrito metas para este curso") }}
    </div>
@endforelse

resources/views/partials/courses/jumbotron.blade.php
<div class="row mb-4">
    <div class="col-md-12">
        <div class="card" style="background-image: url('{{ url('/images/jumbotron.png') }}');">
            <div class="text-white text-center d-flex align-items-center py-5 px-4 my-5">
                <div class="col-5">
                    <img class="img-fluid" src="{{ $course->pathAttachment() }}" />
                </div>
                <div class="col-5 text-left">
                    <h1>{{ __("Curso") }}: {{ $course->name }}</h1>
                    <h4>{{ __("Profesor") }}: {{ $course->teacher->user->name }}</h4>
                    <h5>{{ __("Categoría") }}: {{ $course->category->name }}</h5>
                    <h5>{{ __("Fecha de publicación") }}: {{ $course->created_at->format('d/m/Y') }}</h5>
                    <h5>{{ __("Fecha de actualización") }}: {{ $course->updated_at->format('d/m/Y') }}</h5>
                    <h6>{{ __("Estudiantes inscritos") }}: {{ $course->students_count }}</h6>
                    <h6>{{ __("Número de valoraciones") }}: {{ $course->reviews_count }}</h6>
                    @include('partials.courses.rating', ['rating' => $course->custom_rating])
                </div>
                @include('partials.courses.action_button')
            </div>
        </div>
    </div>

</div>

resources/views/partials/courses/rating.blade.php
<div>
    <ul class="list-inline">
        {{--Aqui le pondre depende cuantas estrellas tiene si tiene mas de una estrella
         se le colocara la clase yellow sino no se le pone estrella--}}
        <li class="list-inline-item"><i class="fa fa-star{{ $rating >= 1 ? ' yellow' : '' }}"></i></li>
        <li class="list-inline-item"><i class="fa fa-star{{ $rating >= 2 ? ' yellow' : '' }}"></i></li>
        <li class="list-inline-item"><i class="fa fa-star{{ $rating >= 3 ? ' yellow' : '' }}"></i></li>
        <li class="list-inline-item"><i class="fa fa-star{{ $rating >= 4 ? ' yellow' : '' }}"></i></li>
        <li class="list-inline-item"><i class="fa fa-star{{ $rating >= 5 ? ' yellow' : '' }}"></i></li>
    </ul>
</div>

resources/views/partials/courses/related.blade.php
<div class="col-12 pt-0 mt-4">
    <h2 class="text-muted">
        {{ __("Cursos similares") }}
    </h2>
    <hr />
</div>
<div class="container-fluid">
    <div class="row">
        @forelse($related as $relatedCourse)
            <div class="col-md-6 listing-block">
                <div class="media">
                    <div class="fav-box">
                        <i class="fa fa-heart-o" aria-hidden="true"></i>
                    </div>
                    <a href="{{ route('courses.detail', $relatedCourse->slug) }}">
                        <img
                            class="d-flex align-self-start"
                            src="/images/courses/{{ $relatedCourse->picture }}"
                            alt="{{ $relatedCourse->name }}"
                        />
                    </a>
                    <div class="media-body pl-3">
                        <div class="price">
                            <small>{{ $relatedCourse->name }}</small>
                        </div>
                        <div class="stats">
                            @include('partials.courses.rating', ['rating' => $relatedCourse->custom_rating])
                        </div>
                    </div>
                </div>
            </div>
        @empty
            <div class="alert alert-dark">
                {{ __("No existe ningún curso relacionado") }}
            </div>
        @endforelse
    </div>
</div>

resources/views/partials/courses/requirements.blade.php
<div class="col-12 pt-0 mt-0">
    <h2 class="text-muted">{{ __("Requisitos para tomar el curso") }}</h2>
    <hr />
</div>
@forelse($requirements as $requirement)
    <div class="col-6">
        <div class="card bg-light p-3">
            <p class="mb-0">
                {{ $requirement->requirement }}
            </p>
        </div>
    </div>
@empty
    <div class="alert alert-dark">
        <i class="fa fa-info-circle"></i>
        {{ __("No hay ningún requisito para este curso") }}
    </div>
@endforelse

resources/views/partials/courses/reviews.blade.php
<div class="align-content-center">
    <div class="col-12 pt-0 mt-4">
        <h2 class="text-muted">{{ __("Valoraciones") }}</h2><hr />
    </div>
    <div class="container-fluid">
        <div class="row">
            @forelse($course->reviews as $review)
                <div class="col-md-8 offset-2 listing-block">
                    <div class="media">
                        <img
                            class="img-rounded"
                            src="{{ $review->user->pathAttachment() }}"
                            alt="{{ $review->user->name }}"
                        />
                        <div class="media-body pl-3">
                            @if($review->comment)
                                <div class="price"><small>{{ $review->comment }}</small></div>
                            @endif
                            <div class="stats">
                                {{ $review->created_at->format('d/m/Y') }}
                                @include('partials.courses.rating', ['rating' => $review->rating])
                            </div>
                        </div>
                    </div>
                </div>
            @empty
                <div class="alert alert-dark"><i class="fa fa-info-circle"></i> {{ __("Sin valoraciones todavía") }}</div>
            @endforelse
        </div>
    </div>
</div>

resources/views/partials/courses/teacher_action_buttons.blade.php
<div class="btn-group">
    {{--si el estado del curso esta publicado--}}
    @if((int) $course->status === \App\Course::PUBLISHED)
        <a class="btn btn-course" href="{{ route('courses.detail', ["slug" => $course->slug]) }}">
            <i class="fa fa-eye"></i> {{ __("Detalle") }}
        </a>
        <a class="btn btn-warning text-white" href="{{ route('courses.edit', ["slug" => $course->slug]) }}">
            <i class="fa fa-pencil"></i> {{ __("Editar curso") }}
        </a>
        @include('partials.courses.btn_forms.delete')
        {{--si el curso esta pendiente--}}
    @elseif((int) $course->status === \App\Course::PENDING)
        <a class="btn btn-primary text-white" href="#">
            <i class="fa fa-history"></i> {{ __("Curso pendiente de revisión") }}
        </a>
        <a class="btn btn-course" href="{{ route('courses.detail', ["slug" => $course->slug]) }}">
            <i class="fa fa-eye"></i> {{ __("Detalle") }}
        </a>
        <a class="btn btn-warning text-white" href="{{ route('courses.edit', ["slug" => $course->slug]) }}">
            <i class="fa fa-pencil"></i> {{ __("Editar curso") }}
        </a>
        @include('partials.courses.btn_forms.delete')
        {{--si el curso esta rechazado--}}
    @else
        <a class="btn btn-danger text-white" href="#">
            <i class="fa fa-pause"></i> {{ __("Curso rechazado") }}
        </a>
        @include('partials.courses.btn_forms.delete')
    @endif
</div>